apiVersion: apps/v1
kind: Deployment
metadata:
  name: layer2
  namespace: business-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: layer2
  template:
    metadata:
      labels:
        app: layer2
    spec:
      containers:
        - name: echo
          image: hieutrv/app-layer2:0.0.4
          ports:
            - containerPort: 8080
          env:
            - name: BASE_URL
              value: http://layer3:8080