apiVersion: apps/v1
kind: Deployment
metadata:
  name: layer3
  namespace: business-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: layer3
  template:
    metadata:
      labels:
        app: layer3
    spec:
      containers:
        - name: echo
          image: hieutrv/app-layer3:0.0.3
          ports:
            - containerPort: 8080