apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: business-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app:  {{ .Values.app.name }}
    spec:
      containers:
        - name: echo
          image: ealen/echo-server
          ports:
            - containerPort: 80
          volumnesMounts:
            - name: nfs-volume
              mountPath: /data
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: {{ .Values.app.name }}-pvc