apiVersion: apps/v1
kind: Deployment
metadata:
  name: layer1
  namespace: business-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: layer1
  template:
    metadata:
      labels:
        app: layer1
    spec:
      containers:
        - name: echo
          image: hieutrv/app-layer1:0.0.2
          ports:
            - containerPort: 8080
          env:
            - name: BASE_URL
              value: http://layer2:8080