apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: business-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: echo
          image: hieutrv/img-log:0.0.1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "200Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
              ephemeral-storage: "512Mi"