apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: business-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: echo
          image: hieutrv/img-log:0.0.1
          ports:
            - containerPort: 80